import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Village Mock</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img />
          <a href='/'>All Programs</a>
          <a href='/find-programs'>Find Programs</a>
          <a href='/plan-programs'>Plan Programs</a>
          <a href='/about'>About</a>
          <a href='/donate'>Donate</a>
          <button>Log in</button>
        </nav>
      </header>
      <main className={styles.main}>
      {data.map(evt => <div><h1>{evt.name}</h1> <p>{evt.grade}</p> <p>{evt.date_begin}-{evt.date_end}</p> <p>{evt.location}</p> <button>Register</button> <a href='/'>Learn More</a></div>)}
      </main>
      <footer className={styles.footer}></footer>
    </>
  )
}


export async function getServerSideProps() {
  const { programs } = await import('/data/data.json')
  return {
      props: {
         data: programs, 
      }
  }
  }