import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { AllPrograms } from '../src/components/home/all-programs'


const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Village Mock</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <Link href='/'>Village Logo
          </Link>
          <Link href='/find-programs'>Find Programs
          </Link>
          <Link href='/plan-programs'>Plan Programs
          </Link>
          <Link href='/about'>About
          </Link>
          <Link href='/donate'>Donate
          </Link>
          <button>Log in</button>
        </nav>
      </header>
      <AllPrograms data={data} />
      <footer className={styles.footer}></footer>
    </>
  )
}

export async function getStaticProps() {
  const { programs } = await import('/data/data.json')
  return {
      props: {
         data: programs, 
    }
  };
}

