import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Village Mock</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img />
          <a href='/'>All Programs</a>
          <a href='/find-programs'>Find Programs</a>
          <a href='/plan-programs'>Plan Programs</a>
          <a href='/about'>About</a>
          <a href='/donate'>Donate</a>
          <button>Log in</button>
        </nav>
      </header>
      <main className={styles.main}>
       
      </main>
      <footer className={styles.footer}></footer>
    </>
  )
}
